### ISSUE TITLE
H button showing in wrong scenes.

### ISSUE THREAD

**Issue by Ezriilc** [Ezriilc/HyperEdit#12]
With KSP v1.2 **_full_** release (build 1586), our "H" button (AppLauncherButton) is showing in some wrong scenes.  It's not much of a problem, but it needs to be corrected, as it means something in our code is not right.

The behavior described below in my repro steps is also found with at least one other mod.  See here:
http://forum.kerbalspaceprogram.com/index.php?/topic/34785-12-hyperedit-v153-sep-14-2016-cheat-teleporter-orbitplanet-editor-more/&page=57#comment-2801611

As far as I know, we're properly checking for FLIGHT or TRACKINGCENTER before showing the button, and if memory serves that is how it worked up through KSP v1.2 **_pre_**-release.  See here:
https://github.com/Ezriilc/HyperEdit/blob/master/Source/Core.cs#L93
https://github.com/Ezriilc/HyperEdit/blob/master/Source/Core.cs#L194

To reproduce this, have build 1586 and HyperEdit v1.5.3 installed.
Notice that our button does not show in the Menu scene (as of yet) - this is proper.
Create/Load a sandbox save.
Notice the "H" button is showing in the Space Center scene - it should not.
Load a ship and launch to the Flight scene.
Notice the button properly shows in all the Flight scene views - this is proper.
Switch back to the Space Center scene.
Notice the button is not showing now - this is proper.
Exit to the Main Menu scene.
Notice the button is now showing here - it should not.

If they have time, I hope that @NathanKell or other knowledgeable devs can shed some light on this.
Thanks in advance!

**Comment by linuxgurugamer** [comment]
It's actually a bug in KSP, which I found and fixed in The Janitor's Closet.
Do this test:  Install The Janitor's Closet, then run your tests again.  Let me know, if it solves the problem, I'll see what I can do.

**Comment by Ezriilc** [comment]
I'm not sure if this issue is important enough to worry about, as it really has no effect on game play - especially if it's not actually in our code and might get fixed in a future KSP version.  However, I will do this test to see how it goes.

**Comment by Ezriilc** [comment]
Yep, after installing The Janitor's Closet, the H button no longer show in the menu scene.

**Comment by linuxgurugamer** [comment]
Ok.  I'll find the code and add it.  I believe it has to do with the way you instantiate the mod, and never going away.  It seems to get KSP confused.  I need to write a simple test case and show it to them.

**Comment by Ezriilc** [comment]
Is this issue still an issue?  I think not.  Anyone?

**Comment by fronbow** [comment]
No, it was fixed :)
