### ISSUE TITLE
Lander: Altitude is not set correctly, but "Current" shows correct.

### ISSUE THREAD

**Issue by Ezriilc** [Ezriilc/HyperEdit#15]
I suspect we're reading actual height above terrain, but setting height above sea level.  I could be wrong, so if anyone has insight, please comment here.

**Comment by LorenPechtel** [comment]
I just had an error with the ship lander that immediately felt like this--AGL vs ASL confusion.

**Comment by fronbow** [comment]
This should be fixed now. The Lander View correctly shows Altitude above Ground Level instead of ASL.

**Comment by Ezriilc** [comment]
Thanks, buddy!  That one was little, but annoying.
