### ISSUE TITLE
Windows can appear off screen if moved in fullscreen mode.

### ISSUE THREAD

**Issue by Ezriilc** [Ezriilc/HyperEdit#17]
HyperEdit remembers where you put the windows by recording it in a config file.

If one moves a window to the edge of the screen in fullscreen mode, and then switches KSP to windowed mode, the HE windows can remain off screen.

I'll need to find an elegant way to correct this, and I'm not sure how just yet.  Any input is welcome.

**Comment by linuxgurugamer** [comment]
Add to this that if you position the windows, close the game, start the game and resize the screen such that the windows would appear outside the screen, they will still be off-screen.
I have this fixed, working on the other

**Comment by Ezriilc** [comment]
I will include this in our next full version update - not sure when that will be.

**Comment by linuxgurugamer** [comment]
Personally, for something like this, i'd do a point release

**Comment by Ezriilc** [comment]
Ok.  Does it make sense to wait a bit to see if any other fixes might get done soon?  My uneducated instinct says that lots of releases is bad.
