### ISSUE TITLE
Hyperedit landing window always opens up

### ISSUE THREAD

**Issue by linuxgurugamer** [Ezriilc/HyperEdit#18]
Current version of Hyperedit, always opens the window.  I noticed this while developing Janitor's Closet, but the behaviour persists even in a save which didn't have JC installed at all

**Comment by Ezriilc** [comment]
Are you sure you haven't checked the "Auto Open" option in the Lander view?

**Comment by Ezriilc** [comment]
I am unable to reproduce this without the Lander's "Auto Open" option checked.

**Comment by linuxgurugamer** [comment]
Oh.  I'll have to check to see if that is set, thanks

**Comment by linuxgurugamer** [comment]
Yup, that's what it was
