### ISSUE TITLE
Settings files invalidate ModuleManager's cache

### ISSUE THREAD

**Issue by blowfishpro** [Ezriilc/HyperEdit#26]
Hyperedit stores its settings in various `.cfg` files in `GameData/Kerbaltek/HyperEdit`.  This causes ModuleManager's cache to be invalidated every time they change.

Simplest fix would be to move them to a `PluginData` folder, which is ignored by KSP and MM.

Background on why MM considers these files to be cachable: KSP loads every `.cfg` file that's not in a `PluginData` folder into the game database.  Any change to the game database could affect MM's patching, so MM considers all these files when creating the cache.  HyperEdit does not access the settings via the game database, so there's no need for them to be loaded.

**Comment by Ezriilc** [comment]
This sounds like a perfectly reasonable condition, so I'm happy to address this in HE.

**Comment by Ezriilc** [comment]
@blowfishpro hooked us up with a PR, and my testing says it's all good.

I will also move our .version files for CKAN into the same folder.
