### ISSUE TITLE
Lander is behaving as if coordinates are different now in KSP 1.3.1

### ISSUE THREAD

**Issue by Ezriilc** [Ezriilc/HyperEdit#29]
The behavior is strange, and makes the Lander unusable.  It tends to put the ship inside the planet and/or just makes it explode with very strange results in the map view.

This particular problem seems entirely new with KSP 1.3.1, and not at all like previous quirks of the Lander, which one could work around.

**Comment by eberg86** [comment]
I am having this problem currently. Part of the reason I quit playing about 8 months ago was for this same reason. I have not been back to check however as to what the resolution might have been for that then.

**Comment by fronbow** [comment]
I've been trying to debug this problem for the past 2+ weeks and getting bogged down by ksp calculations/mechanics :-(
After a seemingly productive evening, I think I may have found one of the culprits.
The variable IntermAltitude in Lander.cs is behaving strangely!
I'm currently stepping through the logic of FixedUpdate to find out why it seems to remain constant when I think it should decrease to get closer to the surface or at least nearer to the entered Altitude.

**Comment by Ezriilc** [comment]
I'm very glad that you are working on this, as I'm genuinely lost on this one - I simply don't know enough to even begin.

Please let me know whatever you may learn, and good luck.  Thanks in advance!

**Comment by fronbow** [comment]
Don't worry, I'll update here if anything else jumps out at me!
I have a sneaking suspicion that the altitude thing is what's causing the lat/lon shifts, though it'll take more stepping through the code tomorrow now that I've got a good Watch list set up!

**Comment by eXigentCoder** [comment]
Hey, if it helps with debugging this issue I noticed the following behaviour. 
While trying to get to a lander by the face on Duna from another vessel, I clicked the "Select" button and choose the target. When I warped to it, I was at the correct latitude but the wrong longitude. I kept manually entering in random longitudes until I was at roughly the correct position and landed. Later I entered the co-ordinates that I had manually worked out and again was at a completely different longitude but still the same latitude.

After going through a few cycles of keeping the coordinates the same and clicking "Land" then waiting a bit then "Drop (CAUTION!)" followed by another "Land", I'm starting to think that the planets rotation is having an effect on how the mod is determining the location coordinates.

This would account for why sometimes the ship will teleport inside the planet and blow up

**Comment by Ezriilc** [comment]
@eXigentCoder , thanks very much for your input.  I don't personally know what to do with it, but all applicable information is welcome.

**Comment by fronbow** [comment]
Thanks for this @eXigentCoder I'm still slowly stepping through the source. I thought I'd solved it last week but the results seem to vary depending on the target body.
So far I've managed to get it to teleport me closer to the surface (still cause for random exploding!) but the Longitude calculations don't seem to work at all as expected.

**Comment by fronbow** [comment]
Just a FYI!
I'm still debugging this and trying to find what is going on. FWIW there's some interesting functions in kOS that I might have to borrow for the ground calculations.
So far it seems that any ground calculations that are made above 10km get skewed as soon as the vessel gets within that 10km.

(Wish there was some early code documentation on what the functions here do!!)

Another line of thinking I have is that the number bases are getting mixed up.
e.g. degrees, radians, and decimal.
So we may need something similar to kOS' Geo-coordinates functions that 'normalises' lat and lon into a uniform base?
Another thing that has me curious is that the named places for landing are more successful at getting you to the surface than random coords/altitude. (i.e. you are less likely to spawn under the terrain!!)
If you want to play about with my stuff it's here: https://github.com/fronbow/HyperEdit/tree/testing
(My VS rewrote the tabs/code layout to how I usually do stuff!!)

**Comment by Ezriilc** [comment]
It's all over my head, and so I'm very appreciative of your efforts.

**Comment by chrisverwey** [comment]
I agree with @eXigentCoder assessment. I did pretty much the same process of elimination. Yesterday I read somewhere that MechJeb had the same behaviour in KSP 1.3.1 but that it's now fixed in a recent developer release. I browsed through their commit history and I noticed 2 commits that sound like a possible fix. In commit [#744](https://github.com/MuMech/MechJeb2/commit/fa67bdaa512585118a599c20ca0282cf2943be13) they changed method calls to GetRelSurfacePosition to GetWorldSurfacePosition. This apparently didn't work because in commit [#747](https://github.com/MuMech/MechJeb2/commit/751261a23984c3fea0440933bd630aea14d835d9) they added "- body.position" to the end of the method call.  I noticed that HyperEdit has 4 calls to GetRelSurfacePosition in Lander.cs and I wonder if this doesn't need to be updated? I have no background in coding mods, so I may be way off. Apologies if so.

**Comment by Ezriilc** [comment]
Thanks!  I will take a look at it, just in case I find something simple to change.

**Comment by fronbow** [comment]
Thanks @chrisverwey I must've missed that; time for more playing!

**Comment by fronbow** [comment]
Ok, that worked. Though I was only using 0,0,100 for the lander data.
@Ezriilc do you want to test my testing branch - I've upped a compiled dll to make it easier!
See https://github.com/fronbow/HyperEdit/releases/tag/v1.5.4.2-alpha
It probably needs more testing but I'm going to build a release version (it takes out all the debug stuff at compile time) and play about later without the overhead of having VS in the background!

**Comment by Ezriilc** [comment]
Yes!  I will give that a try.  If you think it's a good fix, then I can publish your build as a BETA on our page.

THANKS!

**Comment by fronbow** [comment]
I'm going to play around with it in my live build as I have more saved coords I can try (with vehicles so I can see if I get near!). If that's all good then we're good to go!
I'm going to look into that freezing resources thing at some point too!

**Comment by Ezriilc** [comment]
All my tests work perfectly.  Great job, @fronbow !  Can you send me a pull request?

**Comment by fronbow** [comment]
Cool, pull request is on its way. It's probably safe to keep it as a separate branch at the moment...unless you want to merge it? I'm not using any rogue debugs so they can stay in and will only compile in for debug releases!

**Comment by Ezriilc** [comment]
I want to make sure all credit is given where due, so I'll add your names to our page, if that's OK with ya'all.  Please let me know if I've missed anyone, and thanks again to you all.
@eXigentCoder
@chrisverwey 
@fronbow

**Comment by Ezriilc** [comment]
@fronbow , I'm still a noob at GIT, so I'm glad to get advice.  Is merging it the simpler way to go?  I think I'm fine with that, or what do you recommend?

**Comment by chrisverwey** [comment]
Fine by me. Just glad I could help.

**Comment by fronbow** [comment]
@Ezriilc As far as I can see, it should be ok to merge.
Ok with me, luckily this username is my username everywhere, even on the KSP forums!

**Comment by chrisverwey** [comment]
So I ran through a few tests this morning on Kerbin. The movement now all looks pretty neat. The only gripe I have is that the altitude seems to be around 1,000 too low on every jump. If you try to teleport to below 1,000 you get the message that you will be below the terrain (which is at least better than exploding). This even happens over the ocean. If I set my altitude to 1,100 then I end up at 100m.

**Comment by fronbow** [comment]
Hi @chrisverwey can you give me some planets+lander data to test this.
I have a feeling I know where the below sea level thing is (I remember commenting the code!!)

**Comment by chrisverwey** [comment]
@fronbow I put in Lat 0, Long 0, Alt 1000 on Kerbin and hit Land and it positions me nicely over the water, but at altitude 158m. Funny enough if I load the coordinates for KSC runway (-0.04, 285.28, 20m) and hit land then I end up at 90m above the runway. If I adjust that to 2000m above the runway and hit land, then I go to exactly 2000m above the runway. If I put in Lat 0, Lat 0, Alt 2000 and hit land, then I arrive at 1158m above 0,0. Something is not happy.

**Comment by fronbow** [comment]
Cheers for this, I'll test it out later and see what's confusing the calculations!

**Comment by Ezriilc** [comment]
The altitude issue has been a thing for quite a while, actually.  For instance, I believe the way it records the CURRENT position is different from how it sets it.  If you click Current, then immediately land, I think it ends up higher than it was.
@fronbow , if you're gonna look into this, then shall I wait to put up a BETA?  I know peeps are eager for this to get done.
Oh yea, and THANKS to everyone.

**Comment by Ezriilc** [comment]
Done.  Since this is up now, there's no big hurry to get the remaining altitude thing fixed.

**Comment by fronbow** [comment]
Yes, for the moment it looks like if you want to land anywhere not near the surface, you can't.
This could be a "hidden feature" in that you should really use the orbit tool if you don't want to land lol.

**Comment by wile1411** [comment]
Height issue seems to be only when over water. Above land the height seems to get set accurately

**Comment by wile1411** [comment]
For the Loading of Co-ordinates, I don't think the co-ordinates used are fixed to the planet surface. If I load up a set of Co-ordinates over land, it works fine. If I time warp a day or so, the same co-ordinates will be somewhere else on the planet (possibly over water) as the planet rotates away from desired coordinate location. 

I suspect there is some extra  transform maths needed to get the desired location to be aligned with the planets surface rotation.

**Comment by fronbow** [comment]
@wile1411 one of the reasons I stepped in to try and help! was that in the previously released build the coords were seemingly random, and the altitude you ended up at invariably involved crashing below the surface!!
From the digging we've been doing, Squad changed how they calculate stuff which changed how the api functions work.
When I'm testing my builds, I'm using KSP Engineer to tell me the coords and ASL/AGL.

**Comment by fronbow** [comment]
So I decided to do some checking of @wile1411 's Height bug. I seemed to have fixed it in my builds so I'm releasing this beta for testing:
https://github.com/fronbow/HyperEdit/releases/tag/v1.5.5.1-beta-3
I've changed the versioning so that it stays in sync with the existing versions on kerbaltek!
I  would appreciate it if people test using this one please :)

**Comment by Ezriilc** [comment]
While all you awesome people are working on this, I've put our .version file back, in order to keep CKAN from thinking we're done with the full release.

**Comment by chrisverwey** [comment]
@fronbow that link you pasted above to BETA-3.dll doesn't work.  Can we get a copy of the latest build plz for testing.

>  403 Forbidden! Sorry, no direct access.

**Comment by chrisverwey** [comment]
@fronbow Never mind. I managed to grab it from the kerbaltek.com downloads page. It seems you weren't "allowed" to just paste the link over here.

**Comment by Ezriilc** [comment]
"403 Forbidden! Sorry, no direct access." means that your trying to hotlink to the file, or your browser is misbehaving - please turn off your plugins or try a different browser.
I've put fronbow's latest build ("BETA-3") in our "Experimentals" section on our site:  http://www.Kerbaltek.com/hyperedit

**Comment by fronbow** [comment]
Apologies, I wasn't aware kerbaltek had hotlinking disabled. (I'll remember that for the future!!)

**Comment by Ezriilc** [comment]
Lemme know if it becomes a problem, I have some other magic doings to do if we need. ;)

**Comment by chrisverwey** [comment]
Thanks yes, I got it from the experimental page.  I was doing some tests just now on Kerbin and the Mun. If I test jumping to say 0,0,2000m I end up at 2000m as expected over the water, but if I jump to 10,-100, 2000m I arrive at 2215m. I happened to glance at Flight Engineer which tells me that I'm exactly 2000m _above terrain_.  I think that might be our problem with the altitude and it only shows up with you're not over water.

**Comment by fronbow** [comment]
@chrisverwey yeah it's a sneaky little bug this one!
More testing ;) thanks for the input data.
Is your Engineer coords matching up with ours?

**Comment by wile1411** [comment]
didn't think to check the engineer Coords to the one in Hyper Edit. I'll download the latest version to test. The comment from chrisverwey sounds like the ALT part of the issue is fixed as I was kind of expecting the ALT to be over terrain and not a fixed ALT. 

Having said that, I did notice that isn't not 100% perfect at preventing spawning below the surface. What do you do when you detect someone having a Altitude that's below the surface? Do you add a fixed amount or do you set a Fixed safe if altitude?

Hoping that all that's left is the Coords issue. :)

**Comment by wile1411** [comment]
Actually if it help, when I first noticed the moving landing location, I went and updated all my Default landing locations (KSC Launch pad, runway, etc...) What I noticed was that the LON value was all I really needed to correct the location. 

Maybe the issue is just in the how the LON value is applied when spawning. LAT seems to be always correct from what I could tell.

**Comment by fronbow** [comment]
@wile1411 I knew Engineer worked so I used that to test against!
Yeah HyperEdit has always had a tendency to crash, as long as I've been using it!
I'm calculating the actual terrain height underneath the vessel. Then after some checks, just add the entered Alt - though if you enter 0 you get a nice spawn thru terrain that corrects itself ;)

**Comment by chrisverwey** [comment]
@fronbow yes, the Lat/Long in Engineer matches just fine. I think that part of the problem is working now. As for the altitude, if the spec says "altitude above terrain" then I'm happy that it's working 100%. I never really noticed how the altitude worked before - I just assumed it was absolute altitude. Either way I'm happy. Exact lat/long is way more important than exact altitude.

**Comment by wile1411** [comment]
@chrisverwey can you try land in a location (leave Landing screen open) wait for craft to actually land, time warp to next morning and hit LAND again? Does that put you in the same location with the new file?

**Comment by fronbow** [comment]
@chrisverwey As far as I know that's a problem with KSP's altitude dial - it always shows Above Sea Level regardless of what's underneath you!
FWIW I've set my Engineer readout to show me both Altitude (Terrain) and Altitude (Sea Level).
I'm currently at 10, -100, 20 - I spawned at 10, -100, 40ish.
AGL = 362cm (Above Ground Level)
ASL = 20m (Above Sea Level)

HTH

**Comment by Ezriilc** [comment]
`var HyperEditsTendencyToCrash = true;`

**Comment by fronbow** [comment]
The current version of the beta is 1.5.5.1 (Windows Explorer should tell you this) ;) It will resume normal ordering next compile which I'm thinking might be a release. Fingers crossed.

**Comment by chrisverwey** [comment]
@wile1411 I did the following steps to test
1. Launch a plane on the runway
2. Hit "current" button then adjust altitude to 100m
3. Hit "land" button. The plane lands calmly
4. Fast forward to the next day, but a different time of day to avoid being in exactly the same place
5. Hit "land" button. The plane went to the exact same place and landed calmly.

@fronbow I noticed that hitting the "current" button places the asl altitude in the coordinates box, not the agl value. So if you hit "current" and then "land" you end up in a different spot (altitude-wise) from where you started.

**Comment by Ezriilc** [comment]
> @fronbow I noticed that hitting the "current" button places the asl altitude in the coordinates box, not the agl value. So if you hit "current" and then "land" you end up in a different spot (altitude-wise) from where you started.

This was what I noticed a while back.  It would be good to fix that.

**Comment by wile1411** [comment]
awesome! I'll still test, but the latest beta sounds like it got to two things I noticed. Great work!

**Comment by Ezriilc** [comment]
Yes, kudos all around.

**Comment by fronbow** [comment]
@chrisverwey @wile1411 @Ezriilc And here's me thinking we could get a release out the door soon ;)
I'm not very good at planes ;) well, getting them into the air so I never think to try with them!
Back to testing asl/agl then. At least the runway will make for a change of scenery ;)

**Comment by fronbow** [comment]
> @chrisverwey 
> I noticed that hitting the "current" button places the asl altitude in the coordinates box, not the agl value. So if you hit "current" and then "land" you end up in a different spot (altitude-wise) from where you started.

So it should be the AGL not ASL that shows in the Lander window?
KSP doesn't make distinguishing between them both very easy!

**Comment by Ezriilc** [comment]
Oh, BTW, someone asked why anyone would want to "Land" very far above the surface.  I sometimes use a very high drop as a way to test airplanes without needing to take off normally.  I also was toying with the idea of having the Lander impart horizontal speed to the craft as it is dropped, and I realize that that may open a large can of worms.

**Comment by wile1411** [comment]
@Ezriilc Imparting horizontal speed is easy! Just set your obit to an altitude of 10K and you'll have all the speed you'll ever need :-P
(Great idea though! If you do that, it might be prudent to put a max limit of how much speed you can add to a spawning craft to avoid above situation)

**Comment by fronbow** [comment]
@Ezriilc ah yes, that makes sense, did I mention I don't really play with aircraft?!
Yes, that will open a can of worms, maybe even a kraken or two ;)
Stick it down as a possible feature request.

**Comment by Ezriilc** [comment]
Yea, ha!
Or, make the velocity a changeable setting, which would allow the player to test how much their craft can handle.

**Comment by Ezriilc** [comment]
"Release the Kraken!"  https://github.com/Ezriilc/HyperEdit/issues/35

**Comment by fronbow** [comment]
lol, I bet you could break KSP that way.
I'll look at that feature request another day!!

**Comment by Ezriilc** [comment]
I just want to say thanks to you all again.  This has been fun!

I've said it before, and I'll say it again:  **Best... community... _EVER_.**

**Comment by Ezriilc** [comment]
I'm looking to you all to tell me explicitly, and/or send a final pull request for a full release.

**Comment by fronbow** [comment]
I just *ahem* "warped" around the Kerbal Solar system and it all seems to be ok, no crashes or terrain collides. Pull request should be with you asap.

**Comment by wile1411** [comment]
whatever you do, I'll test the latest in 11hrs.

**Comment by Ezriilc** [comment]
I've just done a "final" test, and I see that the Lander's difference between "Current" alt and what you get with "Land" is still wrong.  I guess I thought that was fixed today.  Technically it wasn't part of this issue, so if it's not an easy fix, then I'll just create a new issue for it and we'll get it next round.

To reproduce:
Load and launch the "AeroEquus" rocket to the pad.
In the Lander, click "Current" and see that it reads the alt as ~83.
Then click "Land" and see that it puts you far above the pad (83m?).  But, if you change that alt to 1, it puts you down on the surface more or less immediately.

**Comment by fronbow** [comment]
Yeah it's still the AGL vs ASL. It's time-consuming hunting it down. I would consider it a different issue as we seem to have got the lat/lon/alt working better :)

**Comment by Ezriilc** [comment]
Fair enough!  This issue is DONE!
Again, well done, and thanks to everyone.
