### ISSUE TITLE
Planet Editor not loading certain data on game restart.

### ISSUE THREAD

**Issue by Ezriilc** [Ezriilc/HyperEdit#46]
My tests with Mun and/or Kerbin seem fine, but more than one person has reported this, so it really needs to be more exhaustively tested.

**Comment by fronbow** [comment]
I'm just going through the source, trying to work out where it loads in the data - I'm guessing at the moment that the planet data isn't loaded at startup.

**Comment by Ezriilc** [comment]
It may not be Planet Editor that does this - it could just be Orbit Editor making changes to planet orbits.

I'm doing some testing now to see if I can nail this down better.

**Comment by Ezriilc** [comment]
In the latest BETA...
When I test the **_Orbit Editor_** by changing orbits of Kerbin, Mun, Minmus and Duna, they seem to reload as I saved them.
Also, when I use **_Planet Editor_** to change Kerbin's atmosphere (to none), it seems to also work as expected.

So, this issue is not a thing (any longer?).

However...
Data files are being saved to ./GameData/Kerbaltek/PluginData/
I would prefer that they go to ./GameData/Kerbaltek/HyperEdit/
I'll bet someone is going to remind me why they should be in the former.

Also, I think I'm OK with removing Planet Editor entirely.
