### ISSUE TITLE
Planet editor does not change atmospherePressureSeaLevel

### ISSUE THREAD

**Issue by sworisbreathing** [Ezriilc/HyperEdit#52]
In the current HyperEdit 3 beta for KSP 1.4, the planet editor does not seem to change the atmospheric sea-level pressure.

To reproduce:

1. Create a ship in SPH with an atmosphere sensor.
1. Load the ship on the runway.
1. Activate the pressure sensor (right-click and `Toggle Display`). It should read around 100kPa.
1. Open the planet editor and change the `atmospherePressureSeaLevel` value to something else (halve it, double it, copy from another planet... doesn't really matter), and click `Apply`.
1. Note the value on the pressure sensor. It still reads around 100kPa instead of whatever you tried to change it to.

I'm seeing this on KSP 1.4.3 with the making history expansion installed (Mac version). I noticed it because I was trying to test a SSTO design for Eve by copying the conditions to Kerbin, however it doesn't appear to be an issue with the copy function - even editing the value in the planet editor seems to have no effect.

**Comment by Ezriilc** [comment]
I'm sorry for the delay in replying here.

I'm not fluent in C#.  Can you possibly provide a PR to fix this?  Thanks in advance!

**Comment by Ezriilc** [comment]
Just to ping you, @sworisbreathing   ^^

**Comment by Ezriilc** [comment]
There may be something wrong with the code in this PR.  Since I don't really know Git very well, I can't be sure.  In my efforts to merge things, I seem to have borked the project.

**Comment by sworisbreathing** [comment]
@Ezriilc I know Git pretty well. Maybe I can help you get it back on track.

**Comment by sworisbreathing** [comment]
Ok, there seem to be other issues unrelated to this PR. I've figured out how to get it building on my mac. I'll open another PR to get the project building again.

**Comment by Ezriilc** [comment]
I have some PRs that should take care of at least some of this.  I will report back when I figure what is going on.

**Comment by sworisbreathing** [comment]
Definitely `double`.

![2018-07-14_10-37-50](https://user-images.githubusercontent.com/1486524/42718953-15ebd452-8752-11e8-87d1-fe0613d55dbe.png)

I still can't figure out why it doesn't take effect though.

**Comment by sworisbreathing** [comment]
temperature also seems to be affected by this bug. gravity works though.

**Comment by craidler** [comment]
Maybe it recalculates back to original values based on other atmo properties?

**Comment by sworisbreathing** [comment]
found it. it's the `atmospherePressureCurve` (which is conditionally used based on `atmosphereUsePressureCurve`). I'm working on adding it to the editor, but it's basically a wrapper for an array of `Keyframe` objects.

Right now the tricky part is figuring out how to create a text area in C#. The JSON representation is pretty big.

**Comment by craidler** [comment]
https://docs.unity3d.com/ScriptReference/GUI.TextArea.html
